import type { ExpenseBearer } from './receipt';
export type { ExpenseBearer };

export type ResupplyStatus =
  | 'pending'
  | 'approved'
  | 'ordered'
  | 'fulfilled'
  | 'rejected';

export type ResupplySource =
  | 'manual'
  | 'relay-chat'
  | 'restock-app'
  | 'guest-qr'
  | 'sms-surge'
  | 'telegram'
  | 'purchase-link-sms';

/**
 * Which side of the suite the requesting vendor uses. Set by the originating
 * app so turnwrk-cortex and downstream UIs can route by persona:
 *   - 'cleaning'    — turnover cleaner using the Restock /inspect form
 *   - 'maintenance' — technician using the CMMS technician panel / Relay Chat
 */
export type ResupplyVendorType = 'cleaning' | 'maintenance';

/**
 * One requested resupply line.
 *
 * Two origin styles share this shape:
 *   - Restock (catalog-linked): `itemType` is the canonical catalog key
 *     (e.g. 'toilet-paper'); `productId` optionally pins a specific product.
 *   - Hostfix-CMMS (free-text): `name` is a human label (e.g. "dish sponges").
 *
 * At least one of `itemType` or `name` must be set.
 */
export interface ResupplyItem {
  quantity: number;
  itemType?: string;
  name?: string;
  productId?: string;
  note?: string;
  /**
   * Stable local id, optional. Used by hostfix's UI to track line edits; not
   * required when items are ephemeral inside a restock submission.
   */
  id?: string;
}

/** SOP-08 inbound shipment tracking. */
export interface ResupplyShipment {
  id: string;
  carrier?: string;
  trackingNumber?: string;
  expectedArrivalAt?: number;
  receivedAt?: number;
  receivedBy?: string;
  /** Suggest local buy when overdue. */
  localBuySuggestedAt?: number;
}

export interface ResupplyRequest {
  id: string;
  orgId: string;
  propertyId: string;
  status: ResupplyStatus;
  source: ResupplySource;
  items: ResupplyItem[];
  requestedBy?: string;      // user uid OR anonymous token id
  approvedBy?: string;
  fulfilledBy?: string;
  createdAt: number;
  updatedAt: number;
  notes?: string;

  /** SOP-08 request aging — named owner for the queue. */
  assignedTo?: string;
  assignedToName?: string;
  acknowledgedAt?: number;
  acknowledgedBy?: string;

  // Hostfix-CMMS workflow fields — optional because restock writers don't
  // populate them. Kept on the shared type so both apps can read a single
  // canonical document without casting.
  vendorId?: string;
  vendorName?: string;
  /** Chat action item that spawned this request (CMMS extractor). */
  sourceActionItemId?: string;
  /** Chat message the extractor ran on. */
  sourceMessageId?: string;
  /** Work order auto-created on approval. */
  convertedWOId?: string;
  /** Deep link to the restock app for the approver to actually purchase. */
  restockPurchaseUrl?: string;
  /** Guest-QR token that created the request (anonymous flow). */
  tokenId?: string;
  approvedAt?: number;
  orderedAt?: number;
  fulfilledAt?: number;
  rejectedAt?: number;
  rejectedBy?: string;
  rejectionReason?: string;

  /** Vendor persona that originated the request. */
  vendorType?: ResupplyVendorType;

  /** SOP-08 shipment tracking for external fulfillment. */
  shipments?: ResupplyShipment[];

  // Restock-only extension fields. CMMS readers can ignore these; persisted
  // on the canonical doc so a request created via /inspect retains its
  // photo evidence and cleaner attribution.
  cleanerId?: string;
  cleanerName?: string;
  /** Catalog itemType slugs (Restock catalog) — present alongside `items`. */
  itemTypes?: string[];
  notesImageUrls?: string[];
  storagePhotos?: Array<{
    storageId: string;
    storageName: string;
    imageUrls: string[];
  }>;
  /** Auto-created from below-par inspect (SOP-08). */
  autoGeneratedFromPar?: boolean;
}

// ==================== PURCHASE REQUESTS ====================
// One-off, non-consumable purchases (furniture, appliances, decor, …).
// Originates in hostfix-cmms but lives in the shared `purchaseRequests`
// collection so other suite apps can read it.

export type PurchaseRequestStatus =
  | 'pending'
  | 'approved'
  | 'purchased'
  | 'delivered'
  | 'rejected';

export type PurchaseCategory =
  | 'furniture'
  | 'appliance'
  | 'fixture'
  | 'electronics'
  | 'decor'
  | 'other';

export interface PurchaseRequest {
  id: string;
  orgId: string;
  propertyId: string;
  itemName: string;
  quantity?: number;
  category?: PurchaseCategory;
  estimatedCost?: number;
  urgency: 'High' | 'Medium' | 'Low';
  reason?: string;
  status: PurchaseRequestStatus;
  source?: ResupplySource;
  sourceActionItemId?: string;
  sourceMessageId?: string;
  convertedWOId?: string;
  photoUrls?: string[];
  purchaseUrl?: string;
  vendorId?: string;
  vendorName?: string;
  notes?: string;
  createdAt: number;
  updatedAt: number;
  /** Set on approve: owner upgrade, manager ops, or guest damage. */
  expenseBearer?: ExpenseBearer;
  /**
   * Day of spend (unix ms, start of day). Required when expenseBearer is
   * `guest` for later reservation matching.
   */
  purchaseDate?: number;
  approvedAt?: number;
  approvedBy?: string;
  purchasedAt?: number;
  deliveredAt?: number;
  /** Unified intake queue ownership (mirrors resupply aging). */
  assignedTo?: string;
  acknowledgedAt?: number;
}

/**
 * Visual stock evidence projected from Clean into Restock (TURNWRK-171).
 * Written by clean Admin on supply-relevant bounty approval (`bounty.supply_photo`);
 * restock reads for property-scoped burn-signal footholds (prediction later).
 * Doc id: `bounty_{bountyId}` — idempotent if approval retries.
 */
export interface RestockSupplyPhotoSignal {
  id: string;
  orgId: string;
  propertyId: string;
  bookingId: string;
  bountyId: string;
  spotId: string;
  spotLabel: string;
  photoUrl: string;
  source: 'bounty.supply_photo';
  /** Unix ms when the signal was projected. */
  createdAt: number;
}

/** Stable Firestore doc id for a bounty-sourced supply signal. */
export function restockSupplySignalDocId(bountyId: string): string {
  return `bounty_${bountyId}`;
}
